import numpy as np
import matplotlib.pyplot as plt
from typing import List


def channels_histo(
    data_arr: List[np.ndarray],
    detectors: List[int] = [2, 3, 4, 7],
    gates=[0],
    binNum: int = 10000,
    trigger: int = 5,  # new experimental run
    maxTrigDiff=100e-3,
    fsdelay=[0, 0, 0, 0],
    filename="",
    colors=["grey" for i in range(4)],
):
    # dataDic: dictionary with the timestamps generated by data_loading
    # detectors: list of detector strings (e.g. detectors=['lcH','lcV','kcPi','kcV'])
    # gates: list of time gates we want to plot
    # binNum: number of bins
    # trigger: channel used as a trigger, here channel 5, aka QuTau Trigger 3 (new experimental run)
    # maxTrigDiff: maximum time difference between triggers

    syncFast = data_arr[trigger]
    # dictionary where histograms will be stored
    histoDic = {i: [] for i in detectors}

    diffFS = np.diff(syncFast)
    # print(diffFS)
    # maxFSdur = 11e-3
    maxFSdur = np.amax(
        diffFS[diffFS < maxTrigDiff]
    )  # time difference between atoms are excluded
    # print(maxFSdur)
    histotime = np.linspace(0, maxFSdur, binNum)
    binsize = maxTrigDiff / binNum

    for k, det in enumerate(detectors):
        histoDic[det] = np.copy(data_arr[det])
        for i in range(len(syncFast) - 1):
            start = syncFast[i] + fsdelay[det]
            FSdur = syncFast[i + 1] - start + fsdelay[det]
            left = np.searchsorted(histoDic[det], start)
            right = np.searchsorted(histoDic[det], start + FSdur)
            histoDic[det][left:right] = histoDic[det][left:right] - start

        histoDic[det] = np.histogram(histoDic[det], bins=binNum, range=(0, maxFSdur))[0]

    # Plotting of the histograms
    gateColors = plt.cm.jet(np.linspace(0, 1, len(gates)))  # color map is created

    plt.close(filename + " - Trace Histogram")
    afs = 15

    f = plt.figure(filename + " - Trace Histogram", figsize=[10, 7])

    for i in range(len(detectors)):
        ax = f.add_subplot(len(detectors), 1, i + 1)
        ax.plot(
            histotime * 1e3,
            histoDic[detectors[i]],
            "-",
            label=detectors[i],
            color=colors[i],
        )
        ax1 = ax.twinx()
        ax1.plot(
            histotime * 1e3,
            histoDic[detectors[i]] / (len(syncFast) * binsize),
            "-",
            label=detectors[i],
            color=colors[i],
        )
        ax.legend(loc=6, fontsize=afs)
        ax.set_ylabel("# clicks", fontsize=afs)
        ax1.set_ylabel("rate", fontsize=afs)

        ax.tick_params(axis="y", labelsize=afs)
        ax.tick_params(axis="x", labelsize=afs)

        ax1.tick_params(axis="y", labelsize=afs)

        if i == 0:
            ax1.axhline(
                y=2400,
                xmin=histotime[0] * 1e3,
                xmax=histotime[-1] * 1e3,
                color="k",
                ls="--",
            )  # 2-2' pumping dark counts

        if i == 1:
            ax1.axhline(
                y=1600,
                xmin=histotime[0] * 1e3,
                xmax=histotime[-1] * 1e3,
                color="k",
                ls="--",
            )  # 2-2' pumping dark counts

        for i, gate in enumerate(gates):
            ax.axvline(gate * 1e3, color=gateColors[i])
    ax.set_xlabel("Time (ms)", fontsize=afs)

    f.suptitle(filename + " - Trace Histogram")

    plt.tight_layout()

    return f


def plot_gate_3d(
    matrix,
    title,
    file_name,
    fidelity_indices,
    atom_basis,
    photon_basis,
    save_fig: bool = False,
):
    matrix = np.array(matrix)

    joint_basis = [f"{a} ⊗ {p}" for a in atom_basis for p in photon_basis]

    fidelity = sum(matrix[i, j] for i, j in fidelity_indices) / 4

    fig = plt.figure()
    ax = fig.add_subplot(111, projection="3d")

    _x = np.arange(4)
    _y = np.arange(4)
    _xx, _yy = np.meshgrid(_x, _y)
    x, y = _xx.ravel(), _yy.ravel()

    width = depth = 0.6

    # ---- Ideal bars (faded, height = 1 at fidelity indices) ----
    ideal_heights = np.zeros(16)
    for i, j in fidelity_indices:
        ideal_heights[i * 4 + j] = 1.0

    ax.bar3d(
        x,
        y,
        np.zeros_like(ideal_heights),
        width,
        depth,
        ideal_heights,
        alpha=0.15,  # very transparent (reference)
        edgecolor="black",
        linewidth=0.5,
    )

    # ---- Experimental bars (more opaque) ----
    ax.bar3d(
        x,
        y,
        np.zeros_like(matrix.ravel()),
        width,
        depth,
        matrix.ravel(),
        alpha=0.85,  # more opaque
        edgecolor="black",
        linewidth=0.8,
    )

    ax.set_xticks(np.arange(4) + width / 2)
    ax.set_yticks(np.arange(4) + depth / 2)

    ax.set_xticklabels(joint_basis, rotation=45, ha="right")
    ax.set_yticklabels(joint_basis)

    # ax.set_xlabel("Input")
    # ax.set_ylabel("Output")
    ax.set_zlabel("Probability")

    ax.set_zlim(0, 1.05)

    ax.set_title(
        f"{title}\n$F = {fidelity:.2f}$",
        fontsize=25,
        # 'pad' only moves it relative to the axes; 'y' moves it relative to the figure
        y=1.15,
        bbox=dict(
            facecolor="#e8f4f8",
            edgecolor="dodgerblue",
            boxstyle="round,pad=0.4",
            linewidth=2,
            alpha=0.9,
        ),
    )

    # Manual adjustment to shrink the 3D 'cube' area to make room
    plt.subplots_adjust(top=0.75, bottom=0.1)

    if save_fig:
        # Use a high DPI and pad_inches to ensure the box is captured
        plt.savefig(f"./{file_name}.svg", bbox_inches="tight", pad_inches=0.3)
