import numpy as np
import matplotlib.pyplot as plt
from typing import List


def channels_histo(
    data_arr: List[np.ndarray],
    detectors: List[int] = [2, 3, 4, 7],
    gates=[0],
    binNum: int = 10000,
    trigger: int = 5,  # new experimental run
    maxTrigDiff=100e-3,
    fsdelay=[0, 0, 0, 0],
    filename="",
    colors=["grey" for i in range(4)],
):
    # dataDic: dictionary with the timestamps generated by data_loading
    # detectors: list of detector strings (e.g. detectors=['lcH','lcV','kcPi','kcV'])
    # gates: list of time gates we want to plot
    # binNum: number of bins
    # trigger: channel used as a trigger, here channel 5, aka QuTau Trigger 3 (new experimental run)
    # maxTrigDiff: maximum time difference between triggers

    syncFast = data_arr[trigger]
    # dictionary where histograms will be stored
    histoDic = {i: [] for i in detectors}

    diffFS = np.diff(syncFast)
    # print(diffFS)
    # maxFSdur = 11e-3
    maxFSdur = np.amax(
        diffFS[diffFS < maxTrigDiff]
    )  # time difference between atoms are excluded
    # print(maxFSdur)
    histotime = np.linspace(0, maxFSdur, binNum)
    binsize = maxTrigDiff / binNum

    for k, det in enumerate(detectors):
        histoDic[det] = np.copy(data_arr[det])
        for i in range(len(syncFast) - 1):
            start = syncFast[i] + fsdelay[det]
            FSdur = syncFast[i + 1] - start + fsdelay[det]
            left = np.searchsorted(histoDic[det], start)
            right = np.searchsorted(histoDic[det], start + FSdur)
            histoDic[det][left:right] = histoDic[det][left:right] - start

        histoDic[det] = np.histogram(histoDic[det], bins=binNum, range=(0, maxFSdur))[0]

    # Plotting of the histograms
    gateColors = plt.cm.jet(np.linspace(0, 1, len(gates)))  # color map is created

    plt.close(filename + " - Trace Histogram")
    afs = 15

    f = plt.figure(filename + " - Trace Histogram", figsize=[10, 7])

    for i in range(len(detectors)):
        ax = f.add_subplot(len(detectors), 1, i + 1)
        ax.plot(
            histotime * 1e3,
            histoDic[detectors[i]],
            "-",
            label=detectors[i],
            color=colors[i],
        )
        ax1 = ax.twinx()
        ax1.plot(
            histotime * 1e3,
            histoDic[detectors[i]] / (len(syncFast) * binsize),
            "-",
            label=detectors[i],
            color=colors[i],
        )
        ax.legend(loc=6, fontsize=afs)
        ax.set_ylabel("# clicks", fontsize=afs)
        ax1.set_ylabel("rate", fontsize=afs)

        ax.tick_params(axis="y", labelsize=afs)
        ax.tick_params(axis="x", labelsize=afs)

        ax1.tick_params(axis="y", labelsize=afs)

        if i == 0:
            ax1.axhline(
                y=2400,
                xmin=histotime[0] * 1e3,
                xmax=histotime[-1] * 1e3,
                color="k",
                ls="--",
            )  # 2-2' pumping dark counts

        if i == 1:
            ax1.axhline(
                y=1600,
                xmin=histotime[0] * 1e3,
                xmax=histotime[-1] * 1e3,
                color="k",
                ls="--",
            )  # 2-2' pumping dark counts

        for i, gate in enumerate(gates):
            ax.axvline(gate * 1e3, color=gateColors[i])
    ax.set_xlabel("Time (ms)", fontsize=afs)

    f.suptitle(filename + " - Trace Histogram")

    plt.tight_layout()

    return f
